### ISSUE TITLE
Manage Player Status Screen

### ISSUE THREAD

**Issue by wintermute123** [colloqi/piSignage#10]
I wanted to make a comment about the Status circles on the Manage Players screen.  For those of us that are red/green color blind, it's really hard to tell what player is active.  Could you tweak the icon color, or change it to checkmarks and Xs, or add a tooltip that displays the status?

**Comment by colloqi** [comment]
We will do it

**Comment by colloqi** [comment]
Added a tooltip so that the status text is shown  when the mouse pointer is placed on the circle.
