### ISSUE TITLE
iOS App

### ISSUE THREAD

**Issue by joelarcos** [colloqi/piSignage#100]
I'm an iOS developer and would be interested in developing an open-source app for piSignage. 
I manage my players mostly on the road from an iPhone and I find that navigating the web portal on such a small screen is a little tricky at times. An app with a native iOS UI will provide a better user experience.
Is this something piSignage would be interested in?

**Comment by hitesh83** [comment]
Native mobile app, or better simpler mobile UI .
I would be interested as a user.

**Comment by joelarcos** [comment]
@hitesh83 Do you know whom I would contact to get info about API's?

**Comment by hitesh83** [comment]
@joelarcos this is player app repo,
For managing Server side repo is - https://github.com/colloqi/pisignage-server
you can contact @ravibail for API details

**Comment by colloqi** [comment]
https://piathome.com/apidocs/

**Comment by joelarcos** [comment]
Great. I'll start the project and post a link here so that others can contribute.

**Comment by joelarcos** [comment]
I have started working on the iOS app for piSignage. If anyone is interested in contributing here's the link: https://github.com/joelarcos/piSignage-iOS
