### ISSUE TITLE
Trying to make Car traffic page

### ISSUE THREAD

**Issue by bigpappa456** [colloqi/piSignage#106]
I wish to show a live Car traffic page on the Screen, but i really dont know how to create it. Is there some one that allready created one. Maybe you could explain it to me how to make it?

**Comment by hitesh83** [comment]
can you make Car traffic page in html ?
you can either put a url of html (website) in playlist , or schedule html directly in playlist.

**Comment by bigpappa456** [comment]
i understand i have found many websites that offer api, but my knowledge of api connecting and writing it in php or html is very minimal
