### ISSUE TITLE
Stretch video on multiple displays

### ISSUE THREAD

**Issue by Alexandero89** [colloqi/piSignage#108]
Is it possible to show a video stretched on 2 or more displays(players) at the same time?

For example like it is shown here:
https://info-beamer.com/use-cases/raspberry-pi-video-wall

My usecase:
I have a video that i want to upload to my assets. Then i add it to the playlist and choose the players which will show my video.
But the video will be stretched from Display 1 over Displays 2 till Display 3.
So it seems like "one big display"

Thanks

**Comment by colloqi** [comment]
We do not support video wall
