### ISSUE TITLE
Pi 4 - video in 1080x1920 flickers (2.7.3)

### ISSUE THREAD

**Issue by akke911** [colloqi/piSignage#111]
Video in 1080x1920px show lots of flicker. (tested multiple files)

Screen is native set up as portrait so groups -> settings -> orientation is landscape, but its the same flicker is on a testscreen set up as portrait. Resolution 1080p or auto does not make any difference on the flicker.

Video in 1920x1080 in the same group plays just fine.

![Screenshot 2020-02-26 at 13 28 43](https://user-images.githubusercontent.com/41578267/75345784-b2237780-589d-11ea-8ef0-68e16ad2bdb2.png)

**Comment by bruxbl** [comment]
try 
sudo su -

apt update
apt full-upgrade

that fix problem for me 
but still p4 hang on 1080p after half hour of playing playlist

work well on 720p

Best,

**Comment by akke911** [comment]
Thanks, but did not help in my case.

Problem seems to be related to resolution, resized video to 608x1080 works fine.

The p4 hang you have may be temp issues.

**Comment by jimham1020** [comment]
sudo rpi-update fixed this issue for on rpi 4

**Comment by akke911** [comment]
> sudo rpi-update fixed this issue for on rpi 4

Yes, this fixed the issue 🙂
