### ISSUE TITLE
Setting the clock?

### ISSUE THREAD

**Issue by Anarcane** [colloqi/piSignage#113]
Hey. I can't seem to figure out where it's pulling the time from. Right now it's 1:33pm, but my clock on the widget shows 11:03. I set the timezone of my pisignage player to Eastern time, but that didn't seem to have an impact on the widget time.

Thanks for any help!

**Comment by davidecat** [comment]
Hi, have you deployed the group and rebooted the player after setting the time? 
After reboot try to send date command on pishell to see what is the time there...
hope it helps,
cheers
