### ISSUE TITLE
Quiestion - Custom Resolution

### ISSUE THREAD

**Issue by DanteAlu** [colloqi/piSignage#114]
Good day, im trying to create custom layout of 500x500 and play video in it, and it always goes to full screen, im testing it on full hd monitor at the moment. (the video is 500x500, Fit video is set on letterbox)
Testing it with an image works fine(500x500jpg), but the video for some reason dozenth work.
Do i miss something or its a bug?

Regards

**Comment by colloqi** [comment]
Please select the videowindowsize under layout popup (second tab) and enter the values for video window size. It is kind of duplicate as of now

**Comment by DanteAlu** [comment]
IT worked! Thank you i overlooked that part.

Thanks again
