### ISSUE TITLE
PiSignage Local Server Not Working

### ISSUE THREAD

**Issue by GitRasp2** [colloqi/piSignage#15]
-Colby

I am having trouble connecting to the local IP it gives me:
~ WIFI is up and running properly
~ DNS: Ok
~ PING: OK
~ Rebooted and reloaded multiple times

I had it all working about a week ago and now, It boots up just fine and then sits at the "Welcome!" splash screen, it is giving me the IP to connect to, but when I try to connect it tells me that the webpage is not available.  I am looking for any sort of help.

Thanks
--Colby

**Comment by colloqi** [comment]
Colby

Everything looks fine, did you try the URL as http://<IP address>:8000 (notice port number 8000)?

regards
Ravi

**Comment by GitRasp2** [comment]
Yes I did try that, and it still did not work.

I found out that it was a network problem though!  I fixed it and it is up and running!

Thanks for helping.

--Colby
