### ISSUE TITLE
missing change logs

### ISSUE THREAD

**Issue by si458** [colloqi/piSignage#155]
ive updated twice in the past 2 weeks from 3.0.4 to 3.0.5 to 3.0.6

the is no change logs for what these changes are

it would be nice to update the changelog more frequently
OR
show the changes on the web panel when you click the upgrade icon

**Comment by wrldtvlr** [comment]
Agreed - would really be helpful to understand changes.

**Comment by si458** [comment]
@wrldtvlr the release notes where just updated yesterday, 
however i do agree they are slow and it might be better to list the changelog online when you do the upgrade

**Comment by colloqi** [comment]
Sorry, we skip/delay updation of release notes when the changes are minor but urgent fixes. Will try to avoid this as much as possible in the future!
