### ISSUE TITLE
 Black screen between medias

### ISSUE THREAD

**Issue by st4rg33k** [colloqi/piSignage#17]
Hi,
We have black screen between medias.

Hardware: Raspberry Pi 3
Server: Pisignage.com

Videos:
[IMG_1150.mp4.zip](https://github.com/colloqi/piSignage/files/228083/IMG_1150.mp4.zip)

**Comment by colloqi** [comment]
Will look into it

**Comment by navaneetharaopy** [comment]
Hi,

     Few things 
1) Animation was enabled and it was introducing a delay of 1 sec , but was not animating. We have disabled animation and now image transitions should be smooth after first round of caching.
2) Links will take time to load and there will be a gap.
3) In 1.6.0 beta we have a newer version of browser which you can give a try.


regards,
navaneeth

**Comment by st4rg33k** [comment]
Ok. Thanks for your answer.
I will try this.

How install new version of browser ? sudo apt-get install...
The player is in production, i would not have to update all packages...

Regards,
Julien

**Comment by colloqi** [comment]
Julien

By upgrading to new beta version in Software upgrade popup(in Players Screen by pressing orange cloud button) both the Software and Browser will be upgraded.

Regards
ravi
