### ISSUE TITLE
Android app is not showing section containing link/iframe

### ISSUE THREAD

**Issue by psantos9** [colloqi/piSignage#205]
I am running a playlist in a group composed by a Raspberry Pi and an Android device.
The playlist has a 2-zone layout, and on the bottom zone I've set it to show a link.

The Raspberry PI device is showing the bottom link:
<img width="593" alt="Screenshot 2023-02-01 at 21 06 17" src="https://user-images.githubusercontent.com/1428629/216198872-bffd2e67-7663-4723-9dd5-e8faded4dd20.png">

The Android device is not showing the link:
<img width="591" alt="Screenshot 2023-02-01 at 21 14 35" src="https://user-images.githubusercontent.com/1428629/216198904-9f0625a1-33f8-4e07-9732-5d5f958e16fe.png">

Is this a limitation from the android app, or am I missing something here?

Thank you

**Comment by psantos9** [comment]
So I've investigated a bit on this issue and here is more info on it:

**For testing I've defined a three-zone custom layout defined as follows:**
<img width="1183" alt="Screenshot 2023-02-06 at 15 28 48" src="https://user-images.githubusercontent.com/1428629/217055087-b827e749-094d-4614-91b5-4b46bff07592.png">

While inspecting the dom of the player2 app there are a detail that immediately poppep up to my eye. There are two div elements with the same id =_#main_.

![Screenshot 2023-02-06 at 15 35 56](https://user-images.githubusercontent.com/1428629/217058863-30fdb297-5af5-441d-97b1-06d7c26d6f31.png)

Android app only shows the _#main_ container:
![WhatsApp Image 2023-02-06 at 15 57 37](https://user-images.githubusercontent.com/1428629/217060583-77bab80e-d532-4929-b602-e9f09bdf4e73.jpeg)

Player2 app on Chrome shows the correct layout:
![Screenshot 2023-02-06 at 15 50 44](https://user-images.githubusercontent.com/1428629/217059401-8d367394-87a6-4c42-9b99-a8329bd4195d.png)

Any clues here? Thank you

**Comment by AbhijithBn** [comment]
Hi @psantos9 

If you navigate to Player Settings by clicking on the D_PAD Center button, you can see the Player Resolution.
Example: 960x540
<img width="757" alt="Screenshot 2023-02-07 at 11 59 40 AM" src="https://user-images.githubusercontent.com/22598223/217165738-06782db8-1a6e-4621-a99b-c411142e6b56.png">

You have to design your custom layout according to this dimension and deploy it to the player. 
Let us know if this worked.

**Comment by psantos9** [comment]
Hi @AbhijithBn,
I'm seeing that same 960x540 resolution on my android player settings, but the TV is HD (1280 x 720).
Where is this 960x540 value coming from?
Thank you

**Comment by AbhijithBn** [comment]
In Android Player, Group Settings cannot be used to control Display Resolution, Orientation, and Multi Screen layout.

Android devices not only have [different screen sizes](https://developer.android.com/training/multiscreen/screensizes)—handsets, tablets, TVs, etc.—but also have screens with different pixel sizes.
Reference: https://developer.android.com/training/multiscreen/screendensities

**Comment by psantos9** [comment]
Got it. Thank you!
