### ISSUE TITLE
TV Shutdown CEC

### ISSUE THREAD

**Issue by beankylla** [colloqi/piSignage#21]
Hello,

I have CEC compatible TV.

When I setup the "Enable Sleep Timer" I am under the impression that there is no CEC signal send to TV.

Is that supposed to be an active functionality or am I just doing something wrong?

Thanks and have a nice day!

**Comment by navaneetharaopy** [comment]
Due to varied support for CEC from the TVs, we cutoff HDMI signal from our side using tvservice command. Typically TVs switch off after sometime since there is no signal

**Comment by navaneetharaopy** [comment]
fixed in 1.7.5
