### ISSUE TITLE
How to manually upgrade a standalone player not managed by the opensource server or pisignage.com?

### ISSUE THREAD

**Issue by rmscode** [colloqi/piSignage#217]
I plan on implementing a few players and managing them on my own via the API. Since I will not be using the opensource server . . . I was wondering if there is a process to manually upgrade standalone players. I have seen a few scripts in the PiSignage img that appear to be related to manual upgrades.

**Comment by Hanake0** [comment]
If you plan on making your own API, i recommend you take a look at the open source server code, or just fork it and make your changes as needed. No need to reinvent the wheel.

**Comment by Hanake0** [comment]
As i said, if you want to do it via APIs, check the open source server. 
what you want is here https://github.com/colloqi/pisignage-server/blob/233488edfeb215cf12e52841d52aa1c0ea4ac352/app/controllers/players.js#L603

**Comment by rmscode** [comment]
> As i said, if you want to do it via APIs, check the open source server. What you want is here https://github.com/colloqi/pisignage-server/blob/233488edfeb215cf12e52841d52aa1c0ea4ac352/app/controllers/players.js#L603

And as I said . . . I don't intend on using the open source server. I've tried it and don't care for it. What I need to accomplish is rather simple anyway and can be done with a single powershell script using Invoke-RestMethod. I won't be changing the configuration of the players at all once they are set. I have no need for the opensource management server...we have enough servers to manage. 

You can keep repeating yourself if you'd like, but your response still doesn't address my question . . . at all.

**Comment by Hanake0** [comment]
I am not forcing you to use the open source server, my suggestion was that you took a look at the code to see how the update is done. The link on my response was the exact function that triggers the update on the raspberry pi. I was just triyng to give useful information but well, good luck.

**Comment by rmscode** [comment]
🤦‍♂️ Sorry for the misunderstanding. I didn't want to update via the API . . . I don't think that is possible on a standalone player anyway. I do see now how you were trying to be helpful with that link 😬. I've revised my initial post to be more clear.

**Comment by Hanake0** [comment]
I was kinda rude too, so it's understandable. About the upgrade script, from what i saw, the correct script is located at ~/piSignagePro/misc/upgrade.sh and takes 2 arguments, from a quick look, the first argument is the .zip file URL and the second one the file name to save it.

~The only problem is that i don't know the url where the files are saved on the on the pisignage.com domain~
A quick search on the open source server repo shows that it checks for the new versions on the following url format: "http://pisignage.com/releases/piimage" + serverVersion+ ".zip"

The link for the latest image should be https://chaeri.pisignage.com/releases/piimage3.2.8.zip if i'm not mistaken about the latest version.

I don't have time to test it now, but i guess it should work 😁

**Comment by rmscode** [comment]
My man! I wasn't entirely sure about the url at first either, but you seem to have confirmed that for me. I'll give it a try. Thanks.

**Comment by colloqi** [comment]
> I was kinda rude too, so it's understandable. About the upgrade script, from what i saw, the correct script is located at ~/piSignagePro/misc/upgrade.sh and takes 2 arguments, from a quick look, the first argument is the .zip file URL and the second one the file name to save it.
> 
> ~The only problem is that i don't know the url where the files are saved on the pisignage.com domain~ A quick search on the open source server repo shows that it checks for the new versions on the following url format: "http://pisignage.com/releases/piimage" + serverVersion+ ".zip"
> 
> The link for the latest image should be https://pisignage.com/releases/piimage3.2.8.zip if i'm not mistaken about the latest version.
> 
> I don't have time to test it now, but i guess it should work 😁
> 
> Edit: somehow i copied my org user url ex: "[https://hanake0.pisignage.com[...]](https://hanake0.pisignage.com%5B...%5D)", changed to the oficial one


do a node version check on your player (node -v), then the link is

node v6 players https://pisignage.com/releases/piimage3.2.8-v6.zip
node v14 players https://pisignage.com/releases/piimage3.2.8-v14.zip
node v0.10 https://pisignage.com/releases/piimage3.2.8.zip

**Comment by rmscode** [comment]
> > I was kinda rude too, so it's understandable. About the upgrade script, from what i saw, the correct script is located at ~/piSignagePro/misc/upgrade.sh and takes 2 arguments, from a quick look, the first argument is the .zip file URL and the second one the file name to save it.
> > 
> > ~The only problem is that i don't know the url where the files are saved on the pisignage.com domain~ A quick search on the open source server repo shows that it checks for the new versions on the following url format: "http://pisignage.com/releases/piimage" + serverVersion+ ".zip"
> > 
> > The link for the latest image should be https://pisignage.com/releases/piimage3.2.8.zip if i'm not mistaken about the latest version.
> > 
> > I don't have time to test it now, but i guess it should work 😁
> > 
> > Edit: somehow i copied my org user url ex: "[https://hanake0.pisignage.com[...]](https://hanake0.pisignage.com%5B...%5D)", changed to the oficial one
> 
> 
> do a node version check on your player (node -v), then the link is
> 
> node v6 players https://pisignage.com/releases/piimage3.2.8-v6.zip
> node v14 players https://pisignage.com/releases/piimage3.2.8-v14.zip
> node v0.10 https://pisignage.com/releases/piimage3.2.8.zip 
> 
>   

Ah! Okay. That answers my question about what version to try.
