### ISSUE TITLE
Regarding the reboot option in the _settings.json file (3.2.0)

### ISSUE THREAD

**Issue by rmscode** [colloqi/piSignage#219]
I've noticed the following in the _settings.json file:

```
"reboot": {
        "enable": false,
        "time": null
    }
```

However, changing the values do not appear to reboot the player at the specified time. I'm wondering what this is for.

**Comment by AbhijithBn** [comment]
@rmscode  Can you try 
```
"reboot": {
    "enable": true,
    "time": "1970-01-01T03:30:00.000Z",
    "absoluteTime": "09:00"
}
```

Please note that, if your player is connected to your server, then the server settings will override the player settings.

**Comment by AbhijithBn** [comment]
Can you check if a CronJob is created in your Raspberry Pi by checking the output of the following command?
`crontab -l`

**Comment by rmscode** [comment]
> 
Ah . . . so that setting creates a cron job. I can confirm that a cron job has been created for root - `/sbin/reboot && echo piSignage`. It should work if a cron job exists.. Maybe in I missed something during my original testing. I'll try again. Thanks @AbhijithBn

**Comment by rmscode** [comment]
I understand why I believed that it didn't work in my testing.

I assumed that `absoluteTime` was the key that needed to be changed, but its actually `time`.

Future readers, update the time between the angle brackets . . . Don't leave them in the json code though: 
```
"reboot": {
        "enable": false,
        "absoluteTime": "1970-01-01T<00:00>:00.000Z", 
        "time": "09:00"
    }
```
