### ISSUE TITLE
playing since 23:00:00

### ISSUE THREAD

**Issue by beankylla** [colloqi/piSignage#22]
Hello,

when i Log in to 1 pi, I have this statement, next to the "TV" button.

"playing since 23:00:00".

I Never saw it changed and did reboot the pis a couple time (and it was never 23:00:00).

I don't really need the functionality but just so you know :)

Thanks and have a nice day!

**Comment by colloqi** [comment]
Thanks, will correct or remove the same!

**Comment by beankylla** [comment]
Seems to be corrected on pi player 1.7.2 :) will now close the defect! :)

Thanks for the great work!
