### ISSUE TITLE
Long Blackscreen on transition to any Webpage 

### ISSUE THREAD

**Issue by CristianBuschi** [colloqi/piSignage#224]
My PiSignage software runs on an Raspberry Pi 3 B 
Software version: 3.2.8
Browser: Chromium
Transitioning from any asset type to any webpage leads to a long loading time (>5s) and black screen
And its not only on the first load - everytime you transition to a webpage (even if it is the same page) you have a long loading time with a black screen.
Transitioning to other assets like images or videos is almost instant

Has anyone experienced similar issues or does anyone how to fix (or at least improve) this?

Thank you in advance for helping me out :)

**Comment by colloqi** [comment]
You could try "keep webpages in memory" option under Group settings

**Comment by CristianBuschi** [comment]
Sorry for the late awnser
This solved my issue 👍 

Thank you
