### ISSUE TITLE
Lack of support for some .NET 8/WASM features on chromium-browser 92.0.4515.98 running on PiSignage 3.2.0

### ISSUE THREAD

**Issue by rmscode** [colloqi/piSignage#228]
We currently run PiSignage 3.2.0 (Buster) on a Raspberry Pi 3 which comes with chromium-browser 92.0.4515.98. I have tried to update chromium in the past with `apt update` . . . but it doesn't appear in `apt list --upgradable`. PiSignage docs suggest that the best way to update chromium is to upgrade the player software. We're currently limited to versions 3.2.x because we have an older Pi 3's and probably wouldn't be able to update PiSignage until we purchase a newer set of Pis.

Anyway, we use our Pi to display a custom web app using WASM and after our recent update to .NET 8, our WASM app no longer loads chromium-browser 92. Is there a way to manually upgrade the version of chromium-browser that lives in `/usr/lib/chromium-browser` or is the build specific to Raspbian 10 Buster?

**Comment by rmscode** [comment]
After a bit of research, there doesn't appear to be a more recent chromium-browser package available for [Debian Buster](https://packages.debian.org/buster/web/). What's odd is that the most recent version according to that list is 90, but PiSignage 3.2.0 comes with 92. I'm guessing chromium 92 was the most version at the time you were working on 3.2.0 and you built it from source . . . something I don't know how to do!

Anyway, chromium 120 is available for Bullseye & Bookworm, so we'll have to buy some Raspberry Pi 4's and wait for you guys to finish up with your Bookworm build of PiSignage . . . or just run vanilla Raspberry Pi OS in kiosk mode ;)

**Comment by colloqi** [comment]
Hi, we used chromium came with buster then and available with upgrade packages, never built ourselves. We have released 5.0.1 bookworm release instructions at https://pisignage.com/releases/Player2_installation_procedure.html and also will be releasing Pi 5 image this week. You could try the same with Pi 4 or Pi 5

**Comment by rmscode** [comment]
> Hi, we used chromium came with buster then and available with upgrade packages, never built ourselves. We have released 5.0.1 bookworm release instructions at https://pisignage.com/releases/Player2_installation_procedure.html and also will be releasing Pi 5 image this week. You could try the same with Pi 4 or Pi 5

Thank you for the update, Ravi.
