### ISSUE TITLE
Network problem

### ISSUE THREAD

**Issue by st4rg33k** [colloqi/piSignage#23]
Hi !

I have a problem...
In my network i have a TV Box for watching TV given by my operator. The TV Box use IGMPv2 for streaming diffusion.
When i connect the raspberry pi pisignage on the wifi network, the TV froze sometimes :(
I have increase bandwith TV but the problem can't change.

I have run tcpdump on raspberry pi and i see a weird exchange with the router.
The Rpi are 2 ip adress in arp table. Show the picture:

Router ARP Table
<img width="477" alt="antid arp router" src="https://cloud.githubusercontent.com/assets/1897591/15925059/e1973a56-2e35-11e6-8389-fec8c6343287.png">
Wireshark:
<img width="926" alt="antid 142" src="https://cloud.githubusercontent.com/assets/1897591/15925060/e1acd0c8-2e35-11e6-9c10-239506a669db.png">
<img width="987" alt="antid 137" src="https://cloud.githubusercontent.com/assets/1897591/15925061/e1b2b9c0-2e35-11e6-98e2-8c4efbeef101.png">

Have you any idea what's happening ?
Thanks a lot !

**Comment by colloqi** [comment]
Hi

In case of Static IP configuration we have noticed there will be two IP addresses assigned due to dhcpd which assigns a DHCP address also. But we did not face any issues because of that.

Are you using Static IP?

regards
Ravi

**Comment by st4rg33k** [comment]
No, i use only DHCP wifi. The ethernet is disconnected.
<img width="458" alt="antid ifconfig" src="https://cloud.githubusercontent.com/assets/1897591/15925986/d763113c-2e39-11e6-9117-9180a02668e5.png">
<img width="306" alt="antid interface" src="https://cloud.githubusercontent.com/assets/1897591/15926019/07542fc0-2e3a-11e6-8c6a-35d063c834d4.png">

**Comment by colloqi** [comment]
With Jessie somethings have changed, can you change "dhcp" word to "manual" in 
a. iface eth0 inet dhcp
b. iface default inet dhcp

and try?

**Comment by colloqi** [comment]
Closing the issue, let us know if it is still the issue?
