### ISSUE TITLE
Wifi SSID name with "space character" is not saved properly.

### ISSUE THREAD

**Issue by gtalarico** [colloqi/piSignage#24]

**Comment by gtalarico** [comment]
Perhaps at least a note should be added?

**Comment by colloqi** [comment]
Scan network seems to have an issue with space character, but we were able to save wifi ssid with space character and connect successfully

**Comment by gtalarico** [comment]
OK. That's good.
Didn't work for m though. I had to rename mule ssid.
I was getting a " invalid argument"  msg. And when I clicked to
reconfigure, it should the ssid with no space

Gui Talarico
[ mobile ]

**Comment by colloqi** [comment]
Ok, got it, we have an issue in Ctrl-N interface whereas I was earlier referring web UI interface. Will fix the issue in next release

**Comment by navaneetharaopy** [comment]
fixed in 1.7.0
