### ISSUE TITLE
Password on re-boot?

### ISSUE THREAD

**Issue by Mkragholm** [colloqi/piSignage#246]
I am running the newest version on a Pi 4+ B.
Every time it needs to reboot it requires the password. (User : Pi, Password : Pi).
This means that when I update software, or if there is a power outage, it will reboot and stop at the password screen. I then need to physically go there, find a ladder (it is mounted on the back of a TV mounted from the celling), hook up a USB keyboard and type "pi". Then we are back in business.

How do I remove this password requirement?

**Comment by hitesh83** [comment]
The issue you mentioned is not a common issue.
So,
you will need to provide more info on how you got piSignage on your pi4, like it was on top of the existing OS, it was an image provided by piSignage, the version of the player app or image used, anything extra you added to the player etc. etc..

**Comment by wrldtvlr** [comment]
I had the same issue when I installed the Bookworm image. SSH into your Pi, then run sudo raspi-config. Under System there's an auto login GUI selection.

**Comment by AbhijithBn** [comment]
It's recommended that you don't make any customisation while writing the piSignage SD Card image using the Raspberry Pi imager since our image comes with all these customizations by default.

Example: Enable SSH, autologin, WiFi setup, etc

**Comment by wrldtvlr** [comment]
I agree - that's the way the older images worked. Not sure why the Bookworm image didn't work that way for me. I had to use raspi-config to set autologin.
