### ISSUE TITLE
How can i upgrade pisignage player?

### ISSUE THREAD

**Issue by beankylla** [colloqi/piSignage#25]
From 1.6.1 or 1.6.3 to 1.7.2

**Comment by beankylla** [comment]
I noticed the changelog was speaking about a version 1.7.9.

I downloaded what seemed like the last up to date version yersteday and it was 1.7.2.

Any way to upgrade to 1.7.9?

Thanks and have a nice day,

BK

**Comment by navaneetharaopy** [comment]
Hi,
    Which Type of server you use? Is it open source OR cloud server (at pisignage.com)

a) If you are using open source you can restart the server and it will fetch the  new release files. And when the player is online click update button.
![image](https://cloud.githubusercontent.com/assets/6571626/18741099/f5d329c0-80ca-11e6-8a21-9f4c1fb22837.png)


b) if your using cloud server(pisignage.com) just click update while player is online and player will be updated to the latest available version.

**Comment by colloqi** [comment]
Closing the issue, let us know if it is still the issue

**Comment by bcherup** [comment]
How do you manually upgrade ?
