### ISSUE TITLE
2 MFA forced even if NONE selected

### ISSUE THREAD

**Issue by Buzzmovies** [colloqi/piSignage#259]
![image](https://github.com/colloqi/piSignage/assets/47455886/fc4c8a72-5ef7-40d5-9a75-e410fc749b3c)

Hello, we have issues where our "Collaborators" are forced to use 2MFA even though NONE were previously selected settings.

Basically, It's like 2 MFA is enforced for everyone by default even if showing NONE

Thank you

**Comment by colloqi** [comment]
Hi, we are enforcing one time email verification for every account for each location of login to avoid unscrupulous logins. If collaborator does not have email it is sent to the account holder's email.

**Comment by Buzzmovies** [comment]
@colloqi , Thank you for your reply. I now understand. 

Question: After one-time verification, is it possible to disable 2MFA or use an authenticator app if no email is associated with the collaborator's account?

**Comment by colloqi** [comment]
Yes, that is preferred and also if the location of login does not change, there is no need for any authentication as well

**Comment by Buzzmovies** [comment]
In other words, it's not a bug, it's a feature 😅
Thank you for the explanation. Have a good day.
