### ISSUE TITLE
How can i delete a player from server?

### ISSUE THREAD

**Issue by beankylla** [colloqi/piSignage#26]
While installing a case on a raspberry pi, i broke the SD card.

I then bought another one and reinstalled pisignage player. 

Now in the server interface I have 2 players that are the same machine.

I would like to delete the "old" one that will never be online again since the SDcard is broken.

Any way to do that?

Thanks and have a nice day!

**Comment by navaneetharaopy** [comment]
Hi,

    Please attach a screenshot.

**Comment by colloqi** [comment]
You could do this under settings
