### ISSUE TITLE
There is no date timer for publishing content

### ISSUE THREAD

**Issue by defender4github** [colloqi/piSignage#27]
Dear,

I want to appreciate this project first. thank you for the work well done.
I observed that there is no date timer for publishing content. just like in cms when you can start the campaign and end it with respect to its contents.

can this be added?

**Comment by colloqi** [comment]
Thanks

Under Group, you can add a playlist & schedule for a duration, or on particular week days/dates or a time duration in a day. Is something else you are talking about?
![screen shot 2016-10-13 at 3 12 35 pm](https://cloud.githubusercontent.com/assets/1736279/19344403/a88c4ed8-9157-11e6-9521-6a0555c3fdb5.png)


regards
Ravi

**Comment by defender4github** [comment]
wow, this is awesome.
but I have not seen this in the local hosting server.
I have just installed it, so I am visiting it via my local ip address.

Please could you assist on how to go about it?

**Comment by navaneetharaopy** [comment]
Hi,
 Which local hosting server your referring to ? 
Is it a) Open source server(port 3000) OR b) raspberry pi interface server(port 8000)?

**Comment by defender4github** [comment]
raspberry port 8000

**Comment by defender4github** [comment]
![image](https://cloud.githubusercontent.com/assets/11826128/19346284/833cbd24-913a-11e6-9d07-8c546fda4f90.png)

**Comment by navaneetharaopy** [comment]
Hi,
Local player interface doesn't include this feature. For that you need to use either
1) https://pisignage.com/lp/
OR
2) https://github.com/colloqi/pisignage-server

**Comment by defender4github** [comment]
hi navan, 
thank you for your prompt response, I had seen this link and i read the info there, but there was no HOWTO  as regards raspberry being used, ubuntu and others were listed.
So i wanna know, if pi can be used as the server as well as the player?
if yes, installation procedure is highly appreciated.
thank you

**Comment by navaneetharaopy** [comment]
Hi,
Currently the open source server depends on other tools which require processing power. Since Raspberry pi is not designed to handle such processing,  Open source pisignage-server can't be hosted and it needs x86 hardware.

**Comment by defender4github** [comment]
Hi,

Appreciated, creating Ubuntu server right now to handle that.

shall report back here

**Comment by navaneetharaopy** [comment]
ok
Follow https://github.com/colloqi/pisignage-server#getting-started

**Comment by defender4github** [comment]
hi
I have done the installation following the link above procedures, but i am stock at starting the server.js file.
error "txxxxn@signage:~/pisignage-server$ sudo node server.js
sudo: node: command not found

help pls

but when i issue -ls command,  the file is listed.

**Comment by navaneetharaopy** [comment]
1) Which type of system you use ? (windows,mac,linux)
2) enter `node -v` in terminal,  the command should return the the nodejs version.
3) Please check `env` and `path` variable, These params should contain reference to nodejs source.
4) How did you install nodejs?

**Comment by defender4github** [comment]
ubuntu 16.04 ---linux

**Comment by navaneetharaopy** [comment]
ok, how did you install Nodejs ?

**Comment by defender4github** [comment]
working now after installing legacy version of it again
but new error when i ran "sudo node server.js"

tgn@signage:~$ cd pisignage-server/
tgn@signage:~/pisignage-server$ sudo node server.js
   info  - socket.io started
Express server listening on port 3000 in development mode
*****************************************************
*     Unable to create media directory, exiting     *
*****************************************************

tgn@signage:~/pisignage-server$ 

help pls

**Comment by defender4github** [comment]
oh, it is working now.

Thank you.

**Comment by navaneetharaopy** [comment]
relative(at the same level) to pisignage-server create `media` folder. In order to store screenshots/thumbnails create a `_thumbnails` directory.

**Comment by defender4github** [comment]
ok,
done, 

please can u guide on how to register my pi player on my local server?

thank u in advance

**Comment by navaneetharaopy** [comment]
There is no registration involved. Either connecting usb keyboard(press Ctrl+n) to player OR http://< raspbery-pi-IP>:8000/settings change server to <your-server-address>:3000

**Comment by defender4github** [comment]
Hi Navan,

thank you so much

**Comment by defender4github** [comment]
Hi
In line with your last post, I am unable to connect to my local server pisignage with my pi player.
what is it i have not done correctly?

**Comment by navaneetharaopy** [comment]
which step did you follow?

**Comment by defender4github** [comment]
connecting usb keyboard(press Ctrl+n)

**Comment by defender4github** [comment]
Is there a config file that i have to change the default 8000 port to 3000?

**Comment by navaneetharaopy** [comment]
Press `Ctrl+n` and select `Config server` option, Change the the existing one with < your-pc-ip-address > :3000  and select ok

**Comment by colloqi** [comment]
1.8000 is local port of player which need not be changed
2.it connects to local server over port 3000, so not changes needed
3. Just make sure under player settings server address is given for e.g. as 192.168.1.10:3000 where 192.168.1.10 is the *server* address
4. If still not connecting, see the log file /home/pi/forever_out.log which should say why it is not connecting

**Comment by defender4github** [comment]
hi,

ok

i will try it once i am back 

thank you

**Comment by defender4github** [comment]
hello

I have done it and it is working great.

thank you.

issue encountered
It does not start running at boot, i mean the server.js file

**Comment by navaneetharaopy** [comment]
In ubuntu either you can enter and command in `~/.bash_profile` OR `~/.bashrc` OR  create a service file/ init script . So that your Nodejs open source server is live when system boots.

**Comment by defender4github** [comment]
thank you done
