### ISSUE TITLE
Cannot sign in to local hosted pisignage server and player

### ISSUE THREAD

**Issue by defender4github** [colloqi/piSignage#28]
In view of the subject matter, I want to reset my pisignage server password, any other means because i changed the  default password and now i can not log on again.

thank you in advance.

**Comment by colloqi** [comment]
This should work

1. go to mongo shell (mongo)
2. use pisignage-dev or pisignage (database based on development or production flag)
3. db.settings.update({},{$set:{authCredentials:{user:"pi",password:"pi"}})

**Comment by defender4github** [comment]
hi,
I have tried it and it is not working.
> show dbs 
replied with 
          admin (empty)
          local   0.76GB
          pisignage-dev (empty)

help please

**Comment by colloqi** [comment]
Hi

Then server login should be pi & pi if the db is empty. are you talking about the player?

**Comment by colloqi** [comment]
default htpasswd file to be put at /home/pi/piSignagePro has one line of content as follows

pi:$apr1$gVJMqj0q$YkBf8Z7hP2XzYFWTUHMEr1

**Comment by defender4github** [comment]
Hello,
thank you so much for the guide. I was able to recover the password using mongo shell.
use pisignage-server
show collections
db.settings.find()

issue resolved.
