### ISSUE TITLE
Can Pisignage run on other boards such Orange Pi one 

### ISSUE THREAD

**Issue by abhishekricky** [colloqi/piSignage#32]
I was wondering can it run on smaller boards with 512MB ram ? 

http://www.orangepi.org/orangepione/ -- one i m talking about

**Comment by navaneetharaopy** [comment]
Currently we support only Raspberry pi(all versions ) , Chrome App & Chromecast.

**Comment by Havbaba** [comment]
Can it run on OrangePi 5B now?
For 4K support?

**Comment by hapishyguy** [comment]
I would rather look for something that plays on android. Pi is scarse and expensive, chromecast is expensive, chrome boxes are expensive.
