### ISSUE TITLE
Player error reporting

### ISSUE THREAD

**Issue by JDL747** [colloqi/piSignage#36]
Hi,

Any idea why I'm getting the following error : 

![screen shot 2017-04-20 at 12 07 11](https://cloud.githubusercontent.com/assets/3844254/25225578/28283f22-25c2-11e7-9285-9236fb3b7429.png)

The Group Settings is as follows : 

![screen shot 2017-04-20 at 12 09 37](https://cloud.githubusercontent.com/assets/3844254/25225615/5522fa08-25c2-11e7-9def-05213eba54d8.png)

![screen shot 2017-04-20 at 12 09 49](https://cloud.githubusercontent.com/assets/3844254/25225618/5a786c68-25c2-11e7-8df8-4b4c22986421.png)

**Comment by colloqi** [comment]
It is a harmless error, there are two places which can initiate a playlist start and if it is already started and it returns with a error. Will reduce the severity in next release.

**Comment by JDL747** [comment]
OK, thanks !

I have a couple of questions regarding Scheduled Playlist: 

1.When setting TV_OFF as default playlist, do I need to check `Play together with scheduled playlist`?

2. On the `Set Timings for Scheduled Playlist` under `Only on Selected Days` if I select only 4 days out of 7, how do I set the dates?

![screen shot 2017-04-20 at 13 26 59](https://cloud.githubusercontent.com/assets/3844254/25228624/626ebf16-25cd-11e7-83e2-4dafd639f664.png)

**Comment by colloqi** [comment]
1. It does not matter, but there is no need to select.
2. Let all the Dates be selected
