### ISSUE TITLE
[Suggestion] Calendar to download new contents

### ISSUE THREAD

**Issue by magaiverpr** [colloqi/piSignage#38]
Hi!

We are testing the piSignage, and I would like to suggest a new feature. Today we are using another Media Signage, and we send the new videos in comercial hour, but we would like that the download of the new media happens only in the dawn (like 2am) to not compromise our bandwith.

Could have a checkbox saying "check for new media between __:__ and __:__" to force they keep checking if there is a downtime in the exactly hour.

Thanks!

**Comment by colloqi** [comment]
This feature is available next to Group Deploy button
