### ISSUE TITLE
Freeze screen when restarting Raspberry Pi !

### ISSUE THREAD

**Issue by JDL747** [colloqi/piSignage#42]
Hi,

I'm having some issues when restarting my Raspberry Pi !

It always stops with "**Kernel Panic**" and the booting didn't continue!

![unnamed](https://user-images.githubusercontent.com/3844254/29488943-6a4af69e-8515-11e7-93ac-f9836feda2fb.jpg)

Have you any ideas where it came from?

Thanks for your help !

**Comment by navaneetharaopy** [comment]
Make sure you have SD card with class 10 rating. And the power requirement for raspberry pi is met 
     (**5v, 2A** https://www.raspberrypi.org/help/faqs/#powerReqs )
Do not plug power from your TV USB port , usually those ports have very less current (~500mA). The above problem could be error in reading a corrupted memory block , So just re-write the SD card with new pisigange [image](https://s3.amazonaws.com/pisignage/pisignage-images/pisignage_1.9.0.img.zip) and power ON.

**Comment by JDL747** [comment]
The fact is, the raspberry pi was working correctly for a long time and it's just happened after a reboot and all the requirements mentioned are met.

**Comment by andernunes** [comment]
Same problem.
Works fine for a time but when reboot i see the PANIC error and I need reflash and renew licence.
Sandisk Ultra 32GB
Oficial RPi power supply
