### ISSUE TITLE
Image asset not being displayed after deploy

### ISSUE THREAD

**Issue by JDL747** [colloqi/piSignage#44]
Hi,

Recently after deploying a new playlist, all images asset is showing like this : 

![unnamed](https://user-images.githubusercontent.com/3844254/32070067-6266b5e8-ba8b-11e7-81cf-ac4929400f94.jpg)

Images that were displaying fine no longer works !

Thanks !

**Comment by navaneetharaopy** [comment]
Hi , the above player is connected to open source server OR cloud-server(pisignage.com) ?

**Comment by JDL747** [comment]
I'm using the cloud server !

I've sent you the logs files !

**Comment by colloqi** [comment]
Closing this issue
