### ISSUE TITLE
How i can remove the banner ***This player is powered by pisignage.com***

### ISSUE THREAD

**Issue by bbeurope** [colloqi/piSignage#48]
Hi, 
I reset the player and now i have this banner
***This player is powered by pisignage.com***
How i can remove it? I dont use the server online. I use it just in local for just one video. 
the id is: ID: 0000-0000-1af6-78ed

Please let me know
Thanks

**Comment by colloqi** [comment]
Please register the player at pisignage.com after signup. The license file will be delivered via email (or can be downloaded as well under subscriptions tab). Copy the license file to the player at /home/pi folder. It should be fine
