### ISSUE TITLE
Rasberry Pi 3b+

### ISSUE THREAD

**Issue by whitten2002** [colloqi/piSignage#52]
Hi, has anybody got pisignage to work on a Raspberry pi 3b+ i'm only getting a rainbow screen

**Comment by colloqi** [comment]
Looks like new Pi 3 B+ will boot only with the latest Raspbian (https://support.thepihut.com/hc/en-us/articles/360000553589-My-Raspberry-Pi-3B-won-t-boot-).

We are working on new Stretch based piSignage image and will release soon. Till then only option to try

if you have an older Pi 3B you can run "sudo apt-get update" followed by "sudo apt-get upgrade" on it... Then swap the MicroSD back into the 3B+
 

Also, note

Power Supply (PSU) - The new Raspberry Pi 3B+ needs more juice than previous models - You'll need an official 5.1V 2.5A power supply (or equivalent).

**Comment by colloqi** [comment]
The latest image supports pi 3b+
