### ISSUE TITLE
Turning off/on the TV with the terminal commands seems to stop the output of the PI

### ISSUE THREAD

**Issue by skizztle** [colloqi/piSignage#55]
So I use the terminal commands (Players>Shell) to turn off the TV then turn it back on. This seems to work fine. Then after about 15 seconds I no longer have an output on the screen. 

Samsung TV HDMI CEC with a Pi 3b.

**Comment by skizztle** [comment]
I can still send shell commands to the Pi and I am on 2.0.

**Comment by colloqi** [comment]
Once you turn off please wait for a minute or so to give the TV-ON command, it should work

**Comment by skizztle** [comment]
Seems to work. Thanks.
