### ISSUE TITLE
Hotter Raspi 3

### ISSUE THREAD

**Issue by cellx** [colloqi/piSignage#60]
![580a179e-c7bd-4f23-86a6-81e5ad24a872](https://user-images.githubusercontent.com/81323/46146896-35cdd480-c264-11e8-8cff-bc1bc867345a.jpeg)

After updating to 2.1.7 my raspi got hotter. 80 degree. That is not normal. It has heatsink

**Comment by ravibail** [comment]
Did you have a look at this? probably you can reprogram the SD card with new 2.1.0 image

1. https://help.pisignage.com/hc/en-us/articles/360015940932-Issue-with-2-1-0-image-

2. https://help.pisignage.com/hc/en-us/articles/360008078852-pi-3b-freeze-or-stop-working-after-few-hours

**Comment by colloqi** [comment]
Assuming that the comments satisfied the question, else please write to support@pisignage.com
