### ISSUE TITLE
Random Playback of Assets

### ISSUE THREAD

**Issue by chellmann** [colloqi/piSignage#61]
This is a Feature-Request.

It would be great if the playlist could be set to "shuffle" mode so that the order of the assets in the Playlist is random.
There is a shuffle-button on the Server but this suffles the assets only once, the player will the assets in the same order.
It would be more dynamical when the Suffle is done by the Player at the beginning of the Playlist.

**Comment by colloqi** [comment]
In 2.7.0, we will shuffle content every cycle
