### ISSUE TITLE
Streaming Content from an Embedded Browser Player 

### ISSUE THREAD

**Issue by Richard-Barrett** [colloqi/piSignage#62]
I would like to use the Pisignage to stream embedded content similar to YouTube instead of using the player. Is this possible?

**Comment by colloqi** [comment]
You could, add the link either as "Video Streaming" or "Live Streaming" type under assets and add it to the playlist.

**Comment by colloqi** [comment]
Assuming that the comments satisfied the question, else please write to support@pisignage.com
