### ISSUE TITLE
Change Time Zone from IST

### ISSUE THREAD

**Issue by stocksterfhnw** [colloqi/piSignage#64]
Hello all,

I am struggling to change the time zone from the IST (Indian Standard Time) to our preferred one. Even though I have tried to change the time zone in all possible ways (copying files back and forth, configuring the time zone directly over the raspi-config interface) we still get the time served in IST when hitting the command "date", even though the time zone is correctly set to UTC (+01:00).

This causes the issue that my time widget shows the wrong time. 

I was unable to find where this IST is hardcoded and was hoping you could give me a hint or tell me whether this is a bug?

Thanks a lot and best regards,

stockster

**Comment by colloqi** [comment]
Hi

If you click gear icon next to player name in players tab, you will get a popup as shown. You could change the time zone there and deploy to group. The player gets the new timezone.

The player timezone is written in /home/pi/.bash_profile file 
<img width="673" alt="screenshot 2018-12-17 at 3 57 41 pm" src="https://user-images.githubusercontent.com/1736279/50081586-dfde4c80-0214-11e9-9329-a9f0d36ba62d.png">


Regards
Ravi

**Comment by hitesh83** [comment]
and if you happen to be on opensource server, this option is just between IP address and group name of player. 

or simply use below commands.

check current time zone
`ls -l /etc/localtime`

Output of above command `stdout: lrwxrwxrwx 1 root root 34 Nov 12 17:11 /etc/localtime -> ../usr/share/zoneinfo/Asia/Kolkata`

change time zone to IST
`sudo timedatectl set-timezone 'Asia/Kolkata'`

Replace **Asia/Kolkata** with any time zone  ([list is here](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones ))

**Comment by stocksterfhnw** [comment]
Hello all,

Thanks for the quick feedback.

> The player timezone is written in /home/pi/.bash_profile file

Was exactly what I was looking for. Case closed.

Best regards,

stockster

**Comment by bcherup** [comment]
Anyway to do this on the devices web portal / control panel ?

**Comment by hitesh83** [comment]
2 replies back screenshot is shared, it is from web portal only.
Also from web portal shell below command can be used.
sudo timedatectl set-timezone 'Asia/Kolkata'


Also from below screen shot check yellow circle, you can set time zone

![image](https://user-images.githubusercontent.com/15059079/76054176-d2d28800-5f95-11ea-99ac-72e76368f72f.png)
