### ISSUE TITLE
Ability for static image (unlimited slide time)

### ISSUE THREAD

**Issue by mstratford** [colloqi/piSignage#72]
Hi there, for special events, we would like to have screens dedicated to playing RTMP streams.

This means, during this period, we would like to have a group that displays only one asset continuously (the stream).

Currently it doesn't look like you can set one asset to be permanent, so when it runs out of the slide duration, it reloads the live stream, causing a drop out.

Can we have it such that a slide time of 0 is allowed and causes it to be left on perminantly (until a new group / schedule is made)?

Cheers,
Matthew.

**Comment by colloqi** [comment]
Hello, although 0 is not allowed now, you could enter a large value like 86400 for a day or 864000 for 10 days and try, will that suffice?

**Comment by rpesta** [comment]
0 would be ideal for (infinite) but can you tell me the maximum value in seconds we can use in the field? I'm attempting this with a weblink but it doesn't appear to value any integer I put in there. Once I get into higher numbers it doesn't appear to utilize the value.
