### ISSUE TITLE
Player name & hostname

### ISSUE THREAD

**Issue by zifnabbe** [colloqi/piSignage#74]
I'm setting up a full new test playground for issue: https://github.com/colloqi/piSignage/issues/68.
I've the problem immediately from the first start: It played one day, but it didn't started up today.

So I've not sorted out what is really causing it... (I've not set tickers yet and I experience already the issue)
So, I'm looking at everything, again :-)

I did change my hostname: sudo hostnamectl set-hostname pi-X

I also noticed that the player name  ("this is my test player") was placed in the hosts file as 
127.0.1.1 this-is-my-test-player

Is this by intention? [this was not the case with my previous player]
Is the 'player name' meant to be the hostname?

The seemingly only difference between the two set ups is the version of the player (2.2.1 is working,  2.3.1 is having the issues noted in #68)

**Comment by colloqi** [comment]
In 2.3.1 we added support to set up hostname which has few restrictions and hence the name change https://stackoverflow.com/questions/3523028/valid-characters-of-a-hostname

If you find the issue #68 I would like to see that player log

**Comment by zifnabbe** [comment]
Well, after adjusting the hostname in the hosts file (to pi-X), the player starts when scheduled.
I'm now going to work out some new tests in the hope to find out about #68. Will let you know when I could trigger it (or not)...
