### ISSUE TITLE
License information for the piSignage player

### ISSUE THREAD

**Issue by abhas** [colloqi/piSignage#78]
I wanted to check the license under which the piSignage player and the custom OS image for RPi is distributed. Essentialy, I wanted to confirm if piSignage is distributed under the terms of a free/open source software license.

Thanks...

**Comment by colloqi** [comment]
It is not free or "open source"

**Comment by abhas** [comment]
Just to clarify, my use of the term "free" is as in "free software" ie. software that provides freedom. I don't use "free" as in "free of charge" but as in "free speech".
