### ISSUE TITLE
[Suggestion] Add a txt file with image info in boot partation

### ISSUE THREAD

**Issue by hitesh83** [colloqi/piSignage#79]
This will help MS-Windows users knowing which version of image is flashed in SD card,
Other wise now we have to put the card in Pi , let it boot fully, then on player ID page we get to know what is the image version etc..

This is very useful when we are dealing with more than 100 RPi with Pisignage.

**Comment by colloqi** [comment]
Nice suggestion!

**Comment by colloqi** [comment]
it is implemented now
