### ISSUE TITLE
Make our own template for notice

### ISSUE THREAD

**Issue by Birssan** [colloqi/piSignage#8]
Hello there,
Is there any way we can make our own template for notice ?
The default one has a max-width to 1000px which is kind of surprising considering we're using 1080p display, it should take the whole width don't you think ?

Anyway, at each update we have to override the t1_template.ejs so we can have our own template (different colors, blocks, etc)

Thanks

**Comment by colloqi** [comment]
We will introduce the same like the one for welcome screen https://pisignage.com/lp/faq/#faq34.

**Comment by Birssan** [comment]
Ok, but won't it be overwritten when we update piSignage ?

**Comment by colloqi** [comment]
You need to upload the template to server or media folder and it will get downloaded after the update.

**Comment by Birssan** [comment]
So you have to upload it as asset on the server ? (if the server is pisignage.com)

**Comment by colloqi** [comment]
Yes

**Comment by Birssan** [comment]
Ok thanks, looking forward to this :)

**Comment by colloqi** [comment]
Addded support for this in the server and it will be there for player webUI in 1.4.0. 

Upload notice_template.ejs using Add Assets -> Upload files. Example is shown in https://github.com/colloqi/piSignage/blob/master/examples/templates/notice_template.ejs (based on the current template)
