### ISSUE TITLE
Assets list in group API does not update with playlist

### ISSUE THREAD

**Issue by BNBlake** [colloqi/piSignage#84]
1. create a playlist
1. add assets to playlist
1. create group and add above playlist to it
1. using API endpoint, get info about the GROUP and observe correct list of assets listed in the group
1. add or remove assets from the playlist in step 1
1. using API endpoint get info about the GROUP and observe the asset list has not changed from step 4 above

Expected: the group asset list updates when the playlist updates

**Comment by colloqi** [comment]
Hi,

We just updated the API documents, please have a look at the deploy flag under group
