### ISSUE TITLE
Support for Raspberry Pi 4

### ISSUE THREAD

**Issue by TomGem** [colloqi/piSignage#87]
Hi!

Is there an ETA for Raspberry Pi 4 support, a Raspbian Buster based player image?

Thanks

**Comment by colloqi** [comment]
We have an early image available at https://pisignage.s3.amazonaws.com/pisignage-images/pisignage_2.4.6.img.zip, but I suggest you wait till next week when we will have a latest image based on last week's Pi 4 OS release. Still things are evolving.
