### ISSUE TITLE
Video duration is not respected when duration is shorter than video length

### ISSUE THREAD

**Issue by Luke1982** [colloqi/piSignage#88]
When I set a video's duration shorter than the actual video length, the video will still just play the full length. In the JSON file on the player (the JSON file that represents the playlist), the duration is set like I set in on the server. Still, the player does not respect the shorter duration.
```json
{
    "name": "standaard",
    "settings": {
        "ticker": {
            "enable": false,
            "behavior": "scroll",
            "textSpeed": 3,
            "rss": {
                "enable": false,
                "link": null,
                "feedDelay": 10
            }
        },
        "ads": {
            "adPlaylist": false,
            "adCount": 1,
            "adInterval": 60
        },
        "audio": {
            "enable": false,
            "random": false,
            "volume": 50
        }
    },
    "assets": [
        {
            "filename": "MM008637___BOUNCING_FRUIT_001___1080p___phantom.mp4",
            "selected": false,
            "isVideo": true,
            "option": {
                "main": false
            },
            "duration": 5,
            "fullscreen": true
        },
        {
            "filename": "weather.html",
            "selected": false,
            "isVideo": false,
            "option": {
                "main": false
            },
            "duration": 10,
            "fullscreen": true
        },
        {
            "filename": "file_example_MP4_1920_18MG.mp4",
            "selected": false,
            "isVideo": true,
            "option": {
                "main": false
            },
            "duration": 30,
            "fullscreen": true
        },
        {
            "filename": "datetime-with-weather.zip",
            "selected": false,
            "isVideo": false,
            "option": {
                "main": false
            },
            "duration": 10,
            "fullscreen": true
        }
    ],
    "layout": "1",
    "templateName": "custom_layout.html",
    "schedule": {},
    "version": 28
}
```
MM008637___BOUNCING_FRUIT_001___1080p___phantom.mp4 duration is set to 5, total video is 15 seconds, the video plays for 15 seconds.

**Comment by colloqi** [comment]
Just to take care that video exit event is honoured before timeout, we add 10 seconds to duration and put the timeout. In this case it matches 15 seconds and matches the video duration!

**Comment by Luke1982** [comment]
Hmm, let me test that some more since I've seen it run much longer than 10 extra seconds...

**Comment by bbp-estu** [comment]
I'm also facing same issue. I have uploaded a mp4 video of 219 seconds. In the playlist, duration is set to 15 sec. But still videos plays until end (whole 219 sec)

**Comment by bbp-estu** [comment]
Update: upgraded software to 2.5.0 (from 2.4.1) and the issue is solved

**Comment by Luke1982** [comment]
What is the publishing date of 2.5.0? I believe I'm still on 2.4.1, so this might also solve my issue. If it does I can close the issue.

**Comment by bbp-estu** [comment]
I'm not sure about published date,maybe recently. You can check under registered players section the version of pisignage and if upgrade available there should be an icon/button to the left of 'terminal' button.
![players](https://user-images.githubusercontent.com/44987768/61989569-3c99b500-aff7-11e9-8e91-b8d52c00fe10.jpg)
