### ISSUE TITLE
Line-break in notice

### ISSUE THREAD

**Issue by Birssan** [colloqi/piSignage#9]
Hello,
Is it possible to support line-break (ie: make a new line) in the body of a notice ?

**Comment by colloqi** [comment]
Can you try <br>?

**Comment by Birssan** [comment]
I haven't tried from the server, but from the client, this does not work, it just displays a <br>. I'm guessing the body is encoded with some function before saving it ?

**Comment by colloqi** [comment]
Looks like it is not working, will correct it

**Comment by colloqi** [comment]
Added support for HTML tags in Title, Description and Footer. Also you can upload custom notice template notice_template.ejs if more customization is needed
