### ISSUE TITLE
Will not boot when set to portrait on RPI4

### ISSUE THREAD

**Issue by bwlange3** [colloqi/piSignage#90]
For some reason when you change the orientation to portrait mode (no matter weather you have a specific resolution set or its set to auto).  I know there is a recommendation for using landscape mode, but I thought I would share that portrait is not working at all.  Hopefully support for this is soon to come.

**Comment by interdif** [comment]
same problem ...

**Comment by interdif** [comment]
any idea for a fix ?

**Comment by colloqi** [comment]
With 2.6.1 image, it should boot, only issue is the hdmi_group and hdmi_mode is set to 1 & 16 (1080p) and legacy mode driver will be used (not fkms). You could change the values in /boot/config.txt for hdmi_group & hdmi_mode to suit your display and display should appear

**Comment by interdif** [comment]
Hi,

It can work with 4k display?

(Only html and img display no video need)

Le mar. 3 déc. 2019 à 10:52, Ravi Bail Bhat <notifications@github.com> a
écrit :

**Comment by colloqi** [comment]
Yes, for portrait mode you may have to program the hdmi_mode value accordingly. use the following in piShell to get the values for your display
tvservice -m DMT
tvservice -m CEA

**Comment by interdif** [comment]
OK thx, I will try that tomorrow

One last question, it is possible to use both hdmi as clone?

Le mar. 3 déc. 2019 à 11:03, Ravi Bail Bhat <notifications@github.com> a
écrit :

**Comment by colloqi** [comment]
For non-video assets, yes

**Comment by interdif** [comment]
Do you know the config options for that?

Le mar. 3 déc. 2019 à 11:07, Ravi Bail Bhat <notifications@github.com> a
écrit :

**Comment by colloqi** [comment]
If both cables are connected on poweron, it should just show up at first screens resolution.

**Comment by interdif** [comment]
OK I try that asap, thx a lot

Le mar. 3 déc. 2019 à 12:04, Ravi Bail Bhat <notifications@github.com> a
écrit :

**Comment by interdif** [comment]
Hi,

Tried to set portrait and set the resolution manually like you said with
the parameters found with the two commands. Sadly it doesn't work, I get a
band of image of 10% the rest is black....

**Comment by interdif** [comment]
Hi,

any idea ??

**Comment by colloqi** [comment]
Can you let us know the player and installation when it is online  at support at pisignage.com? we will see the config.txt options?

**Comment by interdif** [comment]
You mean the player ID? I can let it online but I need to know the config
you want, défaut with portrait so in 1080 or the 4k with default on screen

Le dim. 5 janv. 2020 à 01:49, Ravi Bail Bhat <notifications@github.com> a
écrit :

**Comment by colloqi** [comment]
One of these options should work
- Default with 4K in LANDSCAPE mode and use 2ap or 2bp for layout under playlists (this will make it portrait)
- 1080p resolution and portrait mode under group settings

**Comment by interdif** [comment]
i have tested with  default 4K and changed the layout, it does work for txt and img but not working for html link ... and i need it, also i ave tested PDF and it show a very non center display

**Comment by colloqi** [comment]
Can you send us the screenshot and account info at support at pisignage.com?

**Comment by interdif** [comment]
ok, i will do it today 

if necessary i can give you a ssh

**Comment by interdif** [comment]
i found something, whne i set a webpage with "weblink" with layout 2ap/2bp it dont show in portrait, but when its with "link" it work, problem is i cant set auto scroll and other options then ...

**Comment by interdif** [comment]
and "link" doesnt work with all web pages, some i have tested dont show anyting except black or wite page

**Comment by colloqi** [comment]
weblink needs hardware portrait setting (under Group) to work with 2ap/2bp. link type uses iframe and it does not work for CORS links.
We will raise an internal issue to make weblink work without hardware portrait setting
