### ISSUE TITLE
https links not working

### ISSUE THREAD

**Issue by PhoenixZeroDown** [colloqi/piSignage#92]
Hi there,
when using a https weblink for an asset, it does not show the page, only the grey page not found error. Tried it first with our internal wordpress server and with external google and amazon page for testing purpose. When starting a normal chromium session from ssh the page displays as expected. Something special I'm missing here?

**Comment by colloqi** [comment]
Apologies for late reply :)

Use "webpage" option under Add assets > Add link as this supports CORS pages
