### ISSUE TITLE
PR: add option to disable warning overlays

### ISSUE THREAD

**Issue by hexadecatrienoic** [colloqi/piSignage#93]
This repo doesn't include the source for the player, so I can't make a real PR.

Adding the option `avoid_warnings=1` to `/boot/config.txt` will disable the lightning bolt and thermometer overlays for undervoltage and overtemperature situations. Can a button be added to the device config page to enable/disable this? Currently the solution to enable this is manually editing the file using the ssh login.

**Comment by colloqi** [comment]
Thanks, will do!

**Comment by colloqi** [comment]
Added in 2.6.0
