### ISSUE TITLE
Path Traversal vulnerability

### ISSUE THREAD

**Issue by aegisduck** [colloqi/piSignage#97]
# Describe the bug
### Suggested description of the vulnerability
: A path traversal vulnerability in the web application component of piSignage 2.6 allows a remote attacker authenticated as a low privilege user to download arbitrary files from the Raspberry Pi.

### Attack vector(s)
![66](https://user-images.githubusercontent.com/40930382/68727275-4592ae80-0607-11ea-8f15-7df1a1b2cc3d.png)
　1. Click the Log Download button at the bottom of the 'piSignage' administration page.  

![67](https://user-images.githubusercontent.com/40930382/68726719-bb961600-0605-11ea-818b-60900ffd6e65.png)
　2. HTTP Packet is sent when the button is pressed.  

![68](https://user-images.githubusercontent.com/40930382/68726808-fbf59400-0605-11ea-826a-34a427f05cc3.png)
　3. Change the value of 'file' parameter to `../../../../../../../../../../etc/passwd`.  

![69](https://user-images.githubusercontent.com/40930382/68726876-26dfe800-0606-11ea-98d7-f7f7d84ef6b2.png)
　4. You can see that the /etc/passwd file is read.  

### Affected URL/API(s)
URL: `/api/settings/log`
Parameter: `file`

### Environment
* Raspberry Pi Hardware Version: Model 3B+ Revision: 1.3 Ram: 1 GB Sony UK
* piSignage Version: pisignage_2.6.1.img

**Comment by colloqi** [comment]
Thanks, will sandbox the content, since it happens after login there is one level of check if you secure the webUI or disable altogether as of now

**Comment by aegisduck** [comment]
Thank you for your answer. Are you saying it's not a vulnerability? Does this not apply to the next patch?

**Comment by aegisduck** [comment]
> Thanks, will sandbox the content, since it happens after login there is one level of check if you secure the webUI or disable altogether as of now

Thank you for your answer. Are you saying it's not a vulnerability? Does this not apply to the next patch?

**Comment by colloqi** [comment]
Yes and no, if the password is known, piShell is more dangerous place :) best way is to either block the webUI in such cases using server settings or change the password. However we will fix this vulnerability (it is) in the next release

**Comment by colloqi** [comment]
Fixed in 2.6.4
