### ISSUE TITLE
Replace video

### ISSUE THREAD

**Issue by Nrozas** [colloqi/piSignage#98]
There is an option that allows replacing a video with a new one in the assets area, so that only replacing it also changes it in the playlists??

If there was no possibility, it would be a good option to add it to the system.

For example I have a specific offer that lasts 10 days in several playlists where I have it repeated several times among other videos, but every 10 days I will change it for a new one, instead of uploading the new one and adding it to the playlists I would simply replace the previous video with the new one and it would be updated in the playlist without having to go one by one adding it again.

Thanks for any answer that helps me

**Comment by colloqi** [comment]
Yes, it should work that way, but you need to press 
"Deploy All" or Deploy to groups.

**Comment by Nrozas** [comment]
Thanks for your prompt response but I don't understand. What should work like this? Is there an option to replace one video with another? I can not find it?

**Comment by colloqi** [comment]
Make sure the replacing video has the same name as original one, upload the video, it will overwrite

**Comment by Nrozas** [comment]
>Make sure the replacing video has the same name as original one, upload the video, it will overwrite 

@colloqi Thank you so much, I never thought it was that simple.  A big greeting.
>Make sure the replacing video has the same name as original one, upload the video, it will overwrite 

@colloqi Thank you so much, I never thought it was that simple.  A big greeting.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by joelarcos** [comment]
@Nrozas where is this option to replace a video? I don't see it in the assets section.

**Comment by hitesh83** [comment]
@joelarcos there is no option to click or a button to press.
Just upload new file with exact same name which is already in playlist.
Then Deploy, new file with same name will be sent to player.
