### ISSUE TITLE
Playlist not always available for subusers while they are stored in group/category

### ISSUE THREAD

**Issue by codeagencybe** [colloqi/piSignage#99]
Hello

When adding a playlist to a group and category, any sub user can not always see/access those playlist. 
I select the playlist and click "assign to groups" and select the group. 
The sub user has access enabled to this group. 

Sometimes it loads fine very briefly but most of time it does not and the list stay completely empty for the sub user.
When I go to players it shows the current playlist when sub user is logged in. When I click that link, it returns error about no permission but it is set correctly. 
Again, sometimes it loads fine, sometimes it does not. It's very annoying. 
Sometimes it seems to restore after reloading the page several times by clicking 10~20 times on F5 to refresh.  But this can't be the design by default. 
Any idea why this is happening? 

I'm using the hosted service at pisignage.

**Comment by colloqi** [comment]
Can you let us know your account at support at pisignage.com so that we can have a look. Also let us know  which subuser has this issue
